ALTER TABLE `grade_results`
ADD `grade_faults_1` INT(11),
ADD `grade_faults_2` INT(11),
ADD `grade_faults_3` INT(11),
ADD `grade_faults_4` INT(11),
ADD `grade_faults_5` INT(11),
ADD `grade_faults_6` INT(11),
ADD `grade_faults_7` INT(11),
ADD `grade_faults_8` INT(11);
