ALTER TABLE `classroom` 
ADD COLUMN `schooling` TINYINT(1) NULL,
ADD COLUMN `diff_location` SMALLINT(4) NULL,
ADD COLUMN `course` INT(11) NULL;

ALTER TABLE `instructor_documents_and_address` 
ADD COLUMN `diff_location` SMALLINT(4) NULL;

ALTER TABLE `instructor_identification`
ADD COLUMN `deficiency_type_autism` TINYINT(1) NULL,
ADD COLUMN `deficiency_type_gifted` TINYINT(1) NULL;

ALTER TABLE `school_identification` 
ADD COLUMN `id_difflocation` SMALLINT(4) NULL,
ADD COLUMN `linked_mec` TINYINT(1) NULL,
ADD COLUMN `linked_army` TINYINT(1) NULL,
ADD COLUMN `linked_helth` TINYINT(1) NULL,
ADD COLUMN `linked_other` TINYINT(1) NULL,
ADD COLUMN `regulation_organ` SMALLINT(4) NULL;

ALTER TABLE `school_structure` 
ADD COLUMN `building_otherschool` TINYINT(1) NULL,
ADD COLUMN `energy_supply_generator_alternative` TINYINT(1) NULL,
ADD COLUMN `sewage_fossa_common` TINYINT(1) NULL,
ADD COLUMN `garbage_destination_public` TINYINT(1) NULL,
ADD COLUMN `supply_food` TINYINT(1) NULL,
ADD COLUMN `treatment_garbage_parting_garbage` TINYINT(1) NULL,
ADD COLUMN `treatment_garbage_resuse` TINYINT(1) NULL,
ADD COLUMN `traetment_garbage_inexistent` TINYINT(1) NULL,
ADD COLUMN `dependencies_bathroom_workes` TINYINT(1) NULL,
ADD COLUMN `dependencies_pool` TINYINT(1) NULL,
ADD COLUMN `dependencies_arts_room` TINYINT(1) NULL,
ADD COLUMN `dependencies_music_room` TINYINT(1) NULL,
ADD COLUMN `dependencies_dance_room` TINYINT(1) NULL,
ADD COLUMN `dependencies_multiuse_room` TINYINT(1) NULL,
ADD COLUMN `dependencies_yardzao` TINYINT(1) NULL,
ADD COLUMN `dependencies_vivarium` TINYINT(1) NULL,
ADD COLUMN `dependencies_outside_roomspublic` SMALLINT(4) NULL,
ADD COLUMN `dependencies_indoor_roomspublic` SMALLINT(4) NULL,
ADD COLUMN `dependencies_climate_roomspublic` SMALLINT(4) NULL,
ADD COLUMN `dependencies_acessibility_roomspublic` SMALLINT(4) NULL,
ADD COLUMN `acessability_handrails_guardrails` TINYINT(1) NULL,
ADD COLUMN `acessability_elevator` TINYINT(1) NULL,
ADD COLUMN `acessability_tactile_floor` TINYINT(1) NULL,
ADD COLUMN `acessability_doors_80cm` TINYINT(1) NULL,
ADD COLUMN `acessability_ramps` TINYINT(1) NULL,
ADD COLUMN `acessability_sound_signaling` TINYINT(1) NULL,
ADD COLUMN `acessability_tactile_singnaling` TINYINT(1) NULL,
ADD COLUMN `acessability_visual_signaling` TINYINT(1) NULL,
ADD COLUMN `acessabilty_inexistent` TINYINT(1) NULL,
ADD COLUMN `equipments_scanner` TINYINT(1) NULL,
ADD COLUMN `equipments_qtd_blackboard` SMALLINT(6) NULL,
ADD COLUMN `equipments_qtd_notebookstudent` SMALLINT(6) NULL,
ADD COLUMN `equipments_qtd_tabletstudent` SMALLINT(6) NULL,
ADD COLUMN `equipments_multimedia_collection` TINYINT(1) NULL,
ADD COLUMN `equipments_toys_early` TINYINT(1) NULL,
ADD COLUMN `equipments_scientific_materials` TINYINT(1) NULL,
ADD COLUMN `equipments_equipment_amplification` TINYINT(1) NULL,
ADD COLUMN `equipments_musical_instruments` TINYINT(1) NULL,
ADD COLUMN `equipments_educational_games` TINYINT(1) NULL,
ADD COLUMN `equipments_material_cultural` TINYINT(1) NULL,
ADD COLUMN `equipments_material_sports` TINYINT(1) NULL,
ADD COLUMN `equipments_material_teachingindian` TINYINT(1) NULL,
ADD COLUMN `equipments_material_teachingethnic` TINYINT(1) NULL,
ADD COLUMN `equipments_material_teachingrural` TINYINT(1) NULL,
ADD COLUMN `internet_access_administrative` TINYINT(1) NULL,
ADD COLUMN `internet_access_educative_process` TINYINT(1) NULL,
ADD COLUMN `internet_access_student` TINYINT(1) NULL,
ADD COLUMN `internet_access_community` TINYINT(1) NULL,
ADD COLUMN `internet_access_inexistent` TINYINT(1) NULL,
ADD COLUMN `internet_access_connected_personaldevice` TINYINT(1) NULL,
ADD COLUMN `internet_access_connected_desktop` TINYINT(1) NULL,
ADD COLUMN `internet_access_broadband` TINYINT(1) NULL,
ADD COLUMN `internet_access_local_cable` TINYINT(1) NULL,
ADD COLUMN `internet_access_local_wireless` TINYINT(1) NULL,
ADD COLUMN `internet_access_local_inexistet` TINYINT(1) NULL,
ADD COLUMN `workers_administrative_assistant` SMALLINT(6) NULL,
ADD COLUMN `workers_service_assistant` SMALLINT(6) NULL,
ADD COLUMN `workers_librarian` SMALLINT(6) NULL,
ADD COLUMN `workers_firefighter` SMALLINT(6) NULL,
ADD COLUMN `workers_coordinator_shift` SMALLINT(6) NULL,
ADD COLUMN `workers_speech_therapist` SMALLINT(6) NULL,
ADD COLUMN `workers_nutritionist` SMALLINT(6) NULL,
ADD COLUMN `workers_psychologist` SMALLINT(6) NULL,
ADD COLUMN `workers_cooker` SMALLINT(6) NULL,
ADD COLUMN `workers_support_professionals` SMALLINT(6) NULL,
ADD COLUMN `workers_school_secretary` SMALLINT(6) NULL,
ADD COLUMN `workers_security_guards` SMALLINT(6) NULL,
ADD COLUMN `workers_monitors` SMALLINT(6) NULL,
ADD COLUMN `org_teaching_series_year` TINYINT(1) NULL,
ADD COLUMN `org_teaching_semester_periods` TINYINT(1) NULL,
ADD COLUMN `org_teaching_elementary_cycle` TINYINT(1) NULL,
ADD COLUMN `org_teaching_non_serialgroups` TINYINT(1) NULL,
ADD COLUMN `org_teaching_modules` TINYINT(1) NULL,
ADD COLUMN `org_teaching_regular_alternation` TINYINT(1) NULL,
ADD COLUMN `edcenso_native_languages_fk2` INT(11) NULL,
ADD COLUMN `edcenso_native_languages_fk3` INT(11) NULL,
ADD COLUMN `select_adimission` TINYINT(1) NULL,
ADD COLUMN `booking_enrollment_self_declaredskin` TINYINT(1) NULL,
ADD COLUMN `booking_enrollment_income` TINYINT(1) NULL,
ADD COLUMN `booking_enrollment_public_school` TINYINT(1) NULL,
ADD COLUMN `booking_enrollment_disabled_person` TINYINT(1) NULL,
ADD COLUMN `booking_enrollment_others` TINYINT(1) NULL,
ADD COLUMN `booking_enrollment_inexistent` TINYINT(1) NULL,
ADD COLUMN `website` TINYINT(1) NULL,
ADD COLUMN `community_integration` TINYINT(1) NULL,
ADD COLUMN `space_schoolenviroment` TINYINT(1) NULL,
ADD COLUMN `ppp_updated` TINYINT(1) NULL,
ADD COLUMN `board_organ_association_parent` TINYINT(1) NULL,
ADD COLUMN `board_organ_association_parentinstructors` TINYINT(1) NULL,
ADD COLUMN `board_organ_board_school` TINYINT(1) NULL,
ADD COLUMN `board_organ_student_guild` TINYINT(1) NULL,
ADD COLUMN `board_organ_others` TINYINT(1) NULL,
ADD COLUMN `board_organ_inexistent` TINYINT(1) NULL;

ALTER TABLE `student_documents_and_address` 
ADD COLUMN `diff_location` SMALLINT(4) NULL;

ALTER TABLE `student_enrollment` 
ADD COLUMN `aee_cognitive_functions` TINYINT(1) NULL,
ADD COLUMN `aee_autonomous_life` TINYINT(1) NULL,
ADD COLUMN `aee_curriculum_enrichment` TINYINT(1) NULL,
ADD COLUMN `aee_accessible_teaching` TINYINT(1) NULL,
ADD COLUMN `aee_libras` TINYINT(1) NULL,
ADD COLUMN `aee_portuguese` TINYINT(1) NULL,
ADD COLUMN `aee_soroban` TINYINT(1) NULL,
ADD COLUMN `aee_braille` TINYINT(1) NULL,
ADD COLUMN `aee_mobility_techniques` TINYINT(1) NULL,
ADD COLUMN `aee_caa` TINYINT(1) NULL,
ADD COLUMN `aee_optical_nonoptical` TINYINT(1) NULL;

ALTER TABLE `student_identification` 
ADD COLUMN `id_email` VARCHAR(255) NULL,
ADD COLUMN `resource_zoomed_test_18` TINYINT(1) NULL,
ADD COLUMN `resource_cd_audio` TINYINT(1) NULL,
ADD COLUMN `resource_proof_language` TINYINT(1) NULL,
ADD COLUMN `resource_video_libras` TINYINT(1) NULL,
ADD COLUMN `scholarity` SMALLINT(4) NULL,
ADD COLUMN `no_documents_desc` SMALLINT(4) NULL;
