<?php

enum TFeature: string
{
    // SITE
    case FEAT_SITE_HOME = 'FEAT_SITE_HOME';

    // ALUNOS
    case FEAT_STUDENT_CREATE = 'FEAT_STUDENT_CREATE';
    case FEAT_STUDENT_DELETE = 'FEAT_STUDENT_DELETE';
    case FEAT_STUDENT_UPDATE = 'FEAT_STUDENT_UPDATE';
    case FEAT_STUDENT_INDV_RECORD = 'FEAT_STUDENT_INDV_RECORD';

    // MATRÍCULA
    case FEAT_ENROLLMENT_CREATE = 'FEAT_ENROLLMENT_CREATE';
    case FEAT_ENROLLMENT_DELETE = 'FEAT_ENROLLMENT_DELETE';
    case FEAT_ENROLLMENT_UPDATE = 'FEAT_ENROLLMENT_UPDATE';
    case FEAT_ENROLLMENT_TRANSFER = 'FEAT_ENROLLMENT_TRANSFER';
    case FEAT_ENROLLMENT_ONLINE = 'FEAT_ENROLLMENT_ONLINE';

    // TURMAS
    case FEAT_CLASSROOM_LIST = 'FEAT_CLASSROOM_LIST';
    case FEAT_CLASSROOM_CREATE = 'FEAT_CLASSROOM_CREATE';
    case FEAT_CLASSROOM_UPDATE = 'FEAT_CLASSROOM_UPDATE';
    case FEAT_CLASSROOM_DELETE = 'FEAT_CLASSROOM_DELETE';
    case FEAT_CLASSROOM_UPDATE_PEDAGOGIC = 'FEAT_CLASSROOM_UPDATE_PEDAGOGIC';
    case FEAT_CLASSROOM_UPDATE_LINK_INSTRUCTOR = 'FEAT_CLASSROOM_UPDATE_LINK_INSTRUCTOR';
    case FEAT_CLASSROOM_UPDATE_REMOVE_ENROLLMENT_BATCH = 'FEAT_CLASSROOM_UPDATE_REMOVE_ENROLLMENT_BATCH';
    case FEAT_CLASSROOM_UPDATE_MOVE_ENROLLMENT_BATCH = 'FEAT_CLASSROOM_UPDATE_MOVE_ENROLLMENT_BATCH';

    // ESCOLAS
    case FEAT_SCHOOL_LIST = 'FEAT_SCHOOL_LIST';
    case FEAT_SCHOOL_UPDATE = 'FEAT_SCHOOL_UPDATE';
    case FEAT_SCHOOL_UPDATE_DEFINE_STAGES = 'FEAT_SCHOOL_UPDATE_DEFINE_STAGES';
    case FEAT_SCHOOL_DELETE = 'FEAT_SCHOOL_DELETE';

    // PROFESSORES
    case FEAT_INSTRUCTOR_LIST = 'FEAT_INSTRUCTOR_LIST';
    case FEAT_INSTRUCTOR_UPDATE = 'FEAT_INSTRUCTOR_UPDATE';
    case FEAT_INSTRUCTOR_FREQUENCY = 'FEAT_INSTRUCTOR_FREQUENCY';
    case FEAT_INSTRUCTOR_DELETE = 'FEAT_INSTRUCTOR_DELETE';

    // DIÁRIO ELETRÔNICO
    case FEAT_DIARY_LESSON_PLAN = 'FEAT_DIARY_LESSON_PLAN';
    case FEAT_DIARY_CLASSES = 'FEAT_DIARY_CLASSES';
    case FEAT_DIARY_ATTENDANCE = 'FEAT_DIARY_ATTENDANCE';
    case FEAT_DIARY_CALCULATE_GRADES = 'FEAT_DIARY_CALCULATE_GRADES';
    case FEAT_DIARY_GRADES = 'FEAT_GRADES';
    case FEAT_DIARY_GRADES_BUZIOS = 'FEAT_REPORTCARD';
    case FEAT_DIARY_GRADES_FINAL = 'FEAT_GRADESRELEASE';
    case FEAT_DIARY_FREQ_CLASSCONT = 'FEAT_FREQ_CLASSCONT';
    case FEAT_DIARY_AEE_SHEET = 'FEAT_DIARY_AEE_SHEET';
    case FEAT_DIARY_CLASSBOOK = 'FEAT_DIARY_CLASSBOOK';

    // NOVA MERENDA
    case FEAT_FOODS_MENU_CREATE = 'FEAT_FOODS_MENU_CREATE';
    case FEAT_FOODS_MENU_STOCK = 'FEAT_FOODS_MENU_STOCK';
    case FEAT_FOODS_MENU_REQUESTS = 'FEAT_FOODS_MENU_REQUESTS';
    case FEAT_FOODS_MENU_FARMERS = 'FEAT_FOODS_MENU_FARMERS';
    case FEAT_FOODS_MENU_BIDS = 'FEAT_FOODS_MENU_BIDS';

    // MERENDA ESCOLAR
    case FEAT_LUNCH_MENU_MODULE = 'FEAT_LUNCH_MENU_MODULE'; // (se quiser, pode remover também; deixei caso exista rota legada)

    // CURRÍCULO & CALENDÁRIO
    case FEAT_CURRICULUM_CALENDAR = 'FEAT_CURRICULUM_CALENDAR';
    case FEAT_CURRICULUM_MATRIX = 'FEAT_CURRICULUM_MATRIX';
    case FEAT_CURRICULUM_SCHEDULE = 'FEAT_CURRICULUM_SCHEDULE';

    // ADMINISTRAÇÃO
    case FEAT_ADMIN_GENERAL = 'FEAT_ADMIN_GENERAL';
    case FEAT_USER_CHANGE_PASSWORD = 'FEAT_USER_CHANGE_PASSWORD';

    // GESTÃO POR RESULTADOS
    case FEAT_MANAGEMENT_PERFORMANCE_POWERBI = 'FEAT_MANAGEMENT_PERFORMANCE_POWERBI';
    case FEAT_MANAGEMENT_PERFORMANCE = 'FEAT_DASHBOARD_POWER';

    // RELATÓRIOS
    case FEAT_REPORTS_ACCESS = 'FEAT_REPORTS_ACCESS';

    // QUIZ
    case FEAT_QUIZ_ACCESS = 'FEAT_QUIZ_ACCESS';

    // INTEGRAÇÕES
    case FEAT_INTEGRATIONS_ACCESS = 'FEAT_INTEGRATIONS_ACCESS';
    case FEAT_INTEGRATIONS_CENSO = 'FEAT_INTEGRATIONS_CENSO';
    case FEAT_INTEGRATIONS_SAGRES = 'FEAT_INTEGRATIONS_SAGRES';
    case FEAT_INTEGRATIONS_SAGRES_STATUS_ENROLL = 'FEAT_SAGRES_STATUS_ENROL';
    case FEAT_INTEGRATIONS_GESTAOPRESENTE = 'FEAT_INTEGRATIONS_GESTAOPRESENTE';
    case FEAT_INTEGRATIONS_SEDSP = 'FEAT_SEDSP';
    
    // ALMOXARIFADO
    case FEAT_INVENTORY_DASHBOARD = 'FEAT_INVENTORY_DASHBOARD';
    case FEAT_INVENTORY_CATALOG = 'FEAT_INVENTORY_CATALOG';
    case FEAT_INVENTORY_HISTORY = 'FEAT_INVENTORY_HISTORY';
    case FEAT_INVENTORY_REQUEST = 'FEAT_INVENTORY_REQUEST';
    case FEAT_INVENTORY_ADMIN = 'FEAT_INVENTORY_ADMIN';
    case FEAT_PROFESSIONAL_LIST = 'FEAT_PROFESSIONAL_LIST';
}
