<?php

enum TTask: string
{
    case TASK_HOME = 'TASK_HOME';
    case TASK_STUDENT_MANAGE = 'TASK_STUDENT_MANAGE';
    case TASK_ONLINE_ENROLLMENT = 'TASK_ONLINE_ENROLLMENT';
    case TASK_ENROLLMENT_MANAGE = 'TASK_ENROLLMENT_MANAGE';
    case TASK_CLASSROOM_MANAGE = 'TASK_CLASSROOM_MANAGE';
    case TASK_SCHOOL_MANAGE = 'TASK_SCHOOL_MANAGE';
    case TASK_INSTRUCTOR_MANAGE = 'TASK_INSTRUCTOR_MANAGE';
    case TASK_DIARY_RECORD = 'TASK_DIARY_RECORD';
    case TASK_DIARY_GRADING = 'TASK_DIARY_GRADING';
    case TASK_FOODS_MENU_MANAGE = 'TASK_FOODS_MENU_MANAGE';
    case TASK_LUNCH_MENU_MANAGE = 'TASK_LUNCH_MENU_MANAGE';
    case TASK_CURRICULUM_ACCESS = 'TASK_CURRICULUM_ACCESS';
    case TASK_REPORTS_ACCESS = 'TASK_REPORTS_ACCESS';
    case TASK_INTEGRATIONS_ACCESS = 'TASK_INTEGRATIONS_ACCESS';
    case TASK_ADMIN_GENERAL = 'TASK_ADMIN_GENERAL';
    case TASK_MANAGEMENT_PERFORMANCE = 'TASK_MANAGEMENT_PERFORMANCE';
    case TASK_MANAGEMENT_PERFORMANCE_BI = 'TASK_MANAGEMENT_PERFORMANCE_BI';
    case TASK_QUIZ_ACCESS = 'TASK_QUIZ_ACCESS';
    case TASK_STUDENT_IMC = 'TASK_STUDENT_IMC';
    case TASK_INVENTORY_MANAGE = 'TASK_INVENTORY_MANAGE';
}
