var div = $("<div></div>");
$("body").append(div); 

$(document).ready(function(){
    $(".tag-topbar__toggle").click(function(){
        $("#menu").toggleClass("hidden-menu");
        div.toggleClass("sidebar-cover")
    });
    $(".sidebar-cover").click(function(){
        $("#menu").toggleClass("hidden-menu");
        div.toggleClass("sidebar-cover")
    });
    $("#box-menu").click(function(){
        $("#menu").toggleClass("hidden-menu");
        div.toggleClass("sidebar-cover")
    });
    $(".fullmenu-toggle-button").click(function(){
        $("#menu").toggleClass("hidden-menu");
        div.toggleClass("sidebar-cover")
    });
    $(".sidebar-cover").click(function(){
        $("#menu").toggleClass("hidden-menu");
        div.toggleClass("sidebar-cover")
    });
    $("#box-menu").click(function(){
        $("#menu").toggleClass("hidden-menu");
        div.toggleClass("sidebar-cover")
    });
});