<?php
    $FIELDS = array(
        '00'=>array(
            'COLUMNS'=>42,
        ),
        '10'=>array(
            'COLUMNS'=>107,
        ),
        '20'=>array(
            'COLUMNS'=>65,
        ),
        '20'=>array(
            'COLUMNS'=>65,
        ),
        '30'=>array(
            'COLUMNS'=>26,
        ),
        '40'=>array(
            'COLUMNS'=>13,
        ),
        '50'=>array(
            'COLUMNS'=>43,
        ),
        '51'=>array(
            'COLUMNS'=>21,
        ),
        '60'=>array(
            'COLUMNS'=>39,
        ),
        '70'=>array(
            'COLUMNS'=>29,
        ),
        '80'=>array(
            'COLUMNS'=>24,
        ),
    );

?>
