export const GET_ALL = "GET_ALL";
export const GET_CLASSROOM = "GET_CLASSROOM";
export const GET_REGISTRATION = "GET_REGISTRATION";
export const UPDATE_CLASSROOM = "UPDATE_CLASSROOM";
export const UPDATE_REGISTRATION = "UPDATE_REGISTRATION";
export const GET_ERROR = "GET_ERROR";
