export const GET_STUDENT = "GET_STUDENT";
export const GET_REGISTRATION = "GET_REGISTRATION";
export const GET_ERROR_REGISTRATION = "GET_ERROR_REGISTRATION";
export const GET_PERIOD_REGISTRATION = "GET_PERIOD_REGISTRATION";
