-- 2024-07-09_vw_assistance_type

CREATE OR REPLACE
ALGORITHM = UNDEFINED VIEW `classroom_qtd_students` AS
select
    `c`.`school_inep_fk` AS `school_inep_fk`,
    `c`.`inep_id` AS `inep_id`,
    `c`.`id` AS `id`,
    `c`.`name` AS `name`,
    concat_ws(' - ', concat_ws(':', `c`.`initial_hour`, `c`.`initial_minute`), concat_ws(':', `c`.`final_hour`, `c`.`final_minute`)) AS `time`,
    (case
        `c`.`assistance_type` when 0 then 'NÃO SE APLICA'
        when 1 then 'CLASSE HOSPITALAR'
        when 2 then 'UNIDADE DE ATENDIMENTO SOCIOEDUCATIVO'
        when 3 then 'UNIDADE PRISIONAL ATIVIDADE COMPLEMENTAR'
        when 4 then 'ATIVIDADE COMPLEMENTAR'
        else 'ATENDIMENTO EDUCACIONALESPECIALIZADO (AEE)'
    end) AS `assistance_type`,
    (case
        `c`.`modality` when 1 then 'REGULAR'
        when 2 then 'EDUCAÇÃO ESPECIAL'
        when 3 then 'EJA'
        when 4 then 'NÃO SE APLICA'
        else 'ATENDIMENTO EDUCACIONAL ESPECIALIZADO (AEE)'
    end) AS `modality`,
    `esm`.`name` AS `stage`,
    count(`c`.`id`) AS `students`,
    `c`.`school_year` AS `school_year`,
    `se`.`status` AS `status`
from
    ((`classroom` `c`
join `student_enrollment` `se` on
    ((`c`.`id` = `se`.`classroom_fk`)))
left join `edcenso_stage_vs_modality` `esm` on
    ((`c`.`edcenso_stage_vs_modality_fk` = `esm`.`id`)))
where
    ((`se`.`status` in (1, 6, 7, 8, 9, 10))
        or isnull(`se`.`status`))
group by
    `c`.`id`;


-- 2024-11-07_add_created_and_updated_fields
ALTER TABLE answer
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE attendance
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE auth_assignment
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE calendar
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE calendar_event
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE calendar_stages
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE class
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE classroom
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE classroom_has_course_plan
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE class_board
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE class_contents
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE class_diaries
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE class_faults
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE course_class
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE course_class_has_class_ability
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE course_class_has_class_resource
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE course_class_has_class_type
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE course_class_resources
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE course_class_types
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE course_plan
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE curricular_matrix
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE edcenso_discipline
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE edcenso_school_stages
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE edcenso_stage_vs_modality
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE edcenso_stage_vs_modality_complementary
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE event_pre_registration
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE farmer_foods
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE farmer_register
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_ingredient
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_ingredient_alternatives
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_inventory
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_inventory_received
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_inventory_spent
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_menu
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_menu_meal
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_menu_meal_component
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_notice
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_notice_item
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_notice_vs_food_notice_item
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE food_request
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE frequency_and_mean_by_discipline
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE frequency_by_exam
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE grade
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE grade_old
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE grade_results
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE grade_partial_recovery
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE grade_partial_recovery_weights
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE grade_rules
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE grade_unity
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE grade_unity_modality
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE grade_unity_periods
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE inconsistency_sagres
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE instructor_disciplines
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE instructor_documents_and_address
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE instructor_faults
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE instructor_identification
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE instructor_school
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE instructor_teaching_data
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE instructor_variable_data
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE lunch_inventory
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE lunch_item
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE lunch_meal
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE lunch_meal_portion
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE lunch_menu
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE lunch_menu_meal
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE lunch_portion
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE lunch_received
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE lunch_spent
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE manager_identification
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE professional
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE provision_accounts
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE question
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE question_group
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE question_group_question
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE question_option
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE quiz
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE quiz_question
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE registration
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE resumo_quantidades_matriculas
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE schedule
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE school_configuration
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE school_stages_concept_grades
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE school_identification
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE school_stages
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE school_structure
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE sedsp_school_unities
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE stages_vacancy_pre_registration
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE studentsfile
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE studentsfile2
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE student_disorder
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE student_documents_and_address
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE student_enrollment
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE student_identification
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE student_pre_identification
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE student_restrictions
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE student_vaccine
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE teaching_matrixes
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE unavailability
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE users
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE users_school
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE work_by_discipline
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE work_by_exam
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE _course_class_has_class_type
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE _course_class_types
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

ALTER TABLE _unusedtable_curricular_matrix
ADD COLUMN created_at DATETIME DEFAULT NULL,
ADD COLUMN updated_at DATETIME DEFAULT NULL;

-- 2024-28-06_create_nutritionist

insert into auth_item (name, type, description, bizrule, data) values ('nutritionist', 2, '', NULL, 'N;');

-- 2024-30-06_add_school_saturdays

ALTER TABLE food_menu
ADD COLUMN include_saturday TINYINT(1) DEFAULT 0 NULL;

ALTER TABLE food_ingredient
ADD COLUMN measurement_for_unit ENUM('g', 'ml', 'Kg', 'L');

ALTER TABLE food_ingredient
ADD COLUMN amount_for_unit INT NULL;

