[www]

; if we send this to /proc/self/fd/1, it never appears
access.log = /proc/self/fd/2

; user = www-data
; group = www-data

listen = [::]:9000

pm = dynamic
pm.max_children = 48
pm.start_servers = 15
pm.min_spare_servers = 15
pm.max_spare_servers = 25
pm.max_requests = 500

pm.status_path = /status
ping.path = /ping

; send worker output to stdout/stderr
catch_workers_output = yes

; make all environment variables available to php-fpm at runtime
clear_env = no
