<?php

/**
 * This is the model base class for the table "school_configuration".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SchoolConfiguration".
 *
 * Columns in table "school_configuration" available as properties of the model,
 * followed by relations of table "school_configuration" available as properties of the model.
 *
 * @property integer $id
 * @property string $school_inep_id_fk
 * @property string $morning_initial
 * @property string $morning_final
 * @property string $afternoom_initial
 * @property string $afternoom_final
 * @property string $night_initial
 * @property string $night_final
 * @property string $allday_initial
 * @property string $allday_final
 *
 * @property SchoolIdentification $schoolInepIdFk
 */
abstract class BaseSchoolConfiguration extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'school_configuration';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SchoolConfiguration|SchoolConfigurations', $n);
	}

	public static function representingColumn() {
		return 'school_inep_id_fk';
	}

	public function rules() {
		return array(
			array('school_inep_id_fk', 'required'),
			array('school_inep_id_fk', 'length', 'max'=>8),
			array('morning_initial, morning_final, afternoom_initial, afternoom_final, night_initial, night_final, allday_initial, allday_final', 'safe'),
			array('morning_initial, morning_final, afternoom_initial, afternoom_final, night_initial, night_final, allday_initial, allday_final', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, school_inep_id_fk, morning_initial, morning_final, afternoom_initial, afternoom_final, night_initial, night_final, allday_initial, allday_final', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'schoolInepIdFk' => array(self::BELONGS_TO, 'SchoolIdentification', 'school_inep_id_fk'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'school_inep_id_fk' => null,
			'morning_initial' => Yii::t('app', 'Morning Initial'),
			'morning_final' => Yii::t('app', 'Morning Final'),
			'afternoom_initial' => Yii::t('app', 'Afternoom Initial'),
			'afternoom_final' => Yii::t('app', 'Afternoom Final'),
			'night_initial' => Yii::t('app', 'Night Initial'),
			'night_final' => Yii::t('app', 'Night Final'),
			'allday_initial' => Yii::t('app', 'Allday Initial'),
			'allday_final' => Yii::t('app', 'Allday Final'),
			'schoolInepIdFk' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('school_inep_id_fk', $this->school_inep_id_fk);
		$criteria->compare('morning_initial', $this->morning_initial, true);
		$criteria->compare('morning_final', $this->morning_final, true);
		$criteria->compare('afternoom_initial', $this->afternoom_initial, true);
		$criteria->compare('afternoom_final', $this->afternoom_final, true);
		$criteria->compare('night_initial', $this->night_initial, true);
		$criteria->compare('night_final', $this->night_final, true);
		$criteria->compare('allday_initial', $this->allday_initial, true);
		$criteria->compare('allday_final', $this->allday_final, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}